/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildBoxRouteImport } from './routes/build-box'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CombosRouteImport } from './routes/combos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildBoxRoute = BuildBoxRouteImport.update({
  id: '/build-box',
  path: '/build-box',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build-box': typeof BuildBoxRoute
  '/catalogue': typeof CatalogueRoute
  '/combos': typeof CombosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build-box': typeof BuildBoxRoute
  '/catalogue': typeof CatalogueRoute
  '/combos': typeof CombosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build-box': typeof BuildBoxRoute
  '/catalogue': typeof CatalogueRoute
  '/combos': typeof CombosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/build-box' | '/catalogue' | '/combos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/build-box' | '/catalogue' | '/combos'
  id: '__root__' | '/' | '/build-box' | '/catalogue' | '/combos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildBoxRoute: typeof BuildBoxRoute
  CatalogueRoute: typeof CatalogueRoute
  CombosRoute: typeof CombosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-box': {
      id: '/build-box'
      path: '/build-box'
      fullPath: '/build-box'
      preLoaderRoute: typeof BuildBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildBoxRoute: BuildBoxRoute,
  CatalogueRoute: CatalogueRoute,
  CombosRoute: CombosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
