/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuildBoxRouteImport } from './routes/build-box'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CombosRouteImport } from './routes/combos'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as CombosIndexRouteImport } from './routes/combos.index'
import { Route as CombosSlugRouteImport } from './routes/combos.$slug'
import { Route as AuthenticatedEnquiriesIndexRouteImport } from './routes/_authenticated/enquiries.index'
import { Route as AuthenticatedEnquiriesIdRouteImport } from './routes/_authenticated/enquiries.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildBoxRoute = BuildBoxRouteImport.update({
  id: '/build-box',
  path: '/build-box',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CombosIndexRoute = CombosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CombosRoute,
} as any)
const CombosSlugRoute = CombosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CombosRoute,
} as any)
const AuthenticatedEnquiriesIndexRoute =
  AuthenticatedEnquiriesIndexRouteImport.update({
    id: '/enquiries/',
    path: '/enquiries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnquiriesIdRoute =
  AuthenticatedEnquiriesIdRouteImport.update({
    id: '/enquiries/$id',
    path: '/enquiries/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/build-box': typeof BuildBoxRoute
  '/catalogue': typeof CatalogueRoute
  '/combos': typeof CombosRouteWithChildren
  '/enquiry': typeof EnquiryRoute
  '/track': typeof TrackRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRoute
  '/combos/$slug': typeof CombosSlugRoute
  '/combos/': typeof CombosIndexRoute
  '/enquiries/$id': typeof AuthenticatedEnquiriesIdRoute
  '/enquiries/': typeof AuthenticatedEnquiriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/build-box': typeof BuildBoxRoute
  '/catalogue': typeof CatalogueRoute
  '/enquiry': typeof EnquiryRoute
  '/track': typeof TrackRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRoute
  '/combos/$slug': typeof CombosSlugRoute
  '/combos': typeof CombosIndexRoute
  '/enquiries/$id': typeof AuthenticatedEnquiriesIdRoute
  '/enquiries': typeof AuthenticatedEnquiriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/build-box': typeof BuildBoxRoute
  '/catalogue': typeof CatalogueRoute
  '/combos': typeof CombosRouteWithChildren
  '/enquiry': typeof EnquiryRoute
  '/track': typeof TrackRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/combos/$slug': typeof CombosSlugRoute
  '/combos/': typeof CombosIndexRoute
  '/_authenticated/enquiries/$id': typeof AuthenticatedEnquiriesIdRoute
  '/_authenticated/enquiries/': typeof AuthenticatedEnquiriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/build-box'
    | '/catalogue'
    | '/combos'
    | '/enquiry'
    | '/track'
    | '/dashboard'
    | '/products'
    | '/combos/$slug'
    | '/combos/'
    | '/enquiries/$id'
    | '/enquiries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/build-box'
    | '/catalogue'
    | '/enquiry'
    | '/track'
    | '/dashboard'
    | '/products'
    | '/combos/$slug'
    | '/combos'
    | '/enquiries/$id'
    | '/enquiries'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/build-box'
    | '/catalogue'
    | '/combos'
    | '/enquiry'
    | '/track'
    | '/_authenticated/dashboard'
    | '/_authenticated/products'
    | '/combos/$slug'
    | '/combos/'
    | '/_authenticated/enquiries/$id'
    | '/_authenticated/enquiries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuildBoxRoute: typeof BuildBoxRoute
  CatalogueRoute: typeof CatalogueRoute
  CombosRoute: typeof CombosRouteWithChildren
  EnquiryRoute: typeof EnquiryRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-box': {
      id: '/build-box'
      path: '/build-box'
      fullPath: '/build-box'
      preLoaderRoute: typeof BuildBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/combos/': {
      id: '/combos/'
      path: '/'
      fullPath: '/combos/'
      preLoaderRoute: typeof CombosIndexRouteImport
      parentRoute: typeof CombosRoute
    }
    '/combos/$slug': {
      id: '/combos/$slug'
      path: '/$slug'
      fullPath: '/combos/$slug'
      preLoaderRoute: typeof CombosSlugRouteImport
      parentRoute: typeof CombosRoute
    }
    '/_authenticated/enquiries/': {
      id: '/_authenticated/enquiries/'
      path: '/enquiries'
      fullPath: '/enquiries/'
      preLoaderRoute: typeof AuthenticatedEnquiriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enquiries/$id': {
      id: '/_authenticated/enquiries/$id'
      path: '/enquiries/$id'
      fullPath: '/enquiries/$id'
      preLoaderRoute: typeof AuthenticatedEnquiriesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedEnquiriesIdRoute: typeof AuthenticatedEnquiriesIdRoute
  AuthenticatedEnquiriesIndexRoute: typeof AuthenticatedEnquiriesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedEnquiriesIdRoute: AuthenticatedEnquiriesIdRoute,
  AuthenticatedEnquiriesIndexRoute: AuthenticatedEnquiriesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CombosRouteChildren {
  CombosSlugRoute: typeof CombosSlugRoute
  CombosIndexRoute: typeof CombosIndexRoute
}

const CombosRouteChildren: CombosRouteChildren = {
  CombosSlugRoute: CombosSlugRoute,
  CombosIndexRoute: CombosIndexRoute,
}

const CombosRouteWithChildren =
  CombosRoute._addFileChildren(CombosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuildBoxRoute: BuildBoxRoute,
  CatalogueRoute: CatalogueRoute,
  CombosRoute: CombosRouteWithChildren,
  EnquiryRoute: EnquiryRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
